name: Release Tag

on: push

jobs:
  build-win:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Windows binary
        run: bun run build_win

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packscripts-win
          path: ./packscripts-win.exe

  build-nix:
    name: Build Linux/macOS/ARM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build non-Windows binaries
        run: |
          bun run build_nix
          bun run build_nix_musl
          bun run build_osx
          bun run build_arm
          bun run build_arm_musl

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packscripts-nix
          path: |
            ./packscripts-nix
            ./packscripts-nix-musl
            ./packscripts-osx
            ./packscripts-arm
            ./packscripts-arm-musl

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-win, build-nix]
    permissions:
      contents: write
    if: github.ref_type == 'tag'
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: packscripts-win

      - name: Download Linux/macOS/ARM artifacts
        uses: actions/download-artifact@v4
        with:
          name: packscripts-nix

      - name: Create release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65
        with:
          files: |
            ./packscripts-win.exe
            ./packscripts-nix
            ./packscripts-nix-musl
            ./packscripts-osx
            ./packscripts-arm
            ./packscripts-arm-musl
          generate_release_notes: true
