import path from 'node:path';
import { mkdir, rm } from 'node:fs/promises';
import { ANNOTATED_FILE, MOD_BASE_DIR, PACKAGING, RELATIVE_INSTANCE_DIRECTORY } from '../utils/config';
import { read_saved_mods, type SourceType } from '../utils/mods';
import { is_git_available } from '../utils/git';
import { path_is_directory } from '../utils/fs';
import { run_pool } from '../utils/utils';

type BucketName = 'github' | 'curseforge' | 'modrinth' | 'other';

const BUCKET_NAMES: Record<SourceType, BucketName> = {
    GITHUB: 'github',
    CURSEFORGE: 'curseforge',
    MODRINTH: 'modrinth',
    OTHER: 'other',
};

const MARKER_START = '# === GENERATED BY PACKSCRIPTS IMAGE - DO NOT EDIT ===';
const MARKER_END = '# === END PACKSCRIPTS IMAGE ===';
const LFS_HEADER = 'version https://git-lfs.github.com/spec/v1';
// eslint-disable-next-line @typescript-eslint/naming-convention
const TEN_MiB = 10 * 1024 * 1024;
const MS_PER_DAY = 24 * 60 * 60 * 1000;

const MARKER_RE = new RegExp(`\\n?${re_escape(MARKER_START)}[\\s\\S]*?${re_escape(MARKER_END)}\\n?`, 'm');
interface ImageState {
    promoted: Record<
        string,
        {
            promoted_at: string;
            bucket: string;
            last_score: number;
        }
    >;
}

interface ModEntry {
    mod_id: string;
    file_path: string;
    bucket: BucketName;
    stripped_basename: string;
    freq: number;
    freq_exp: number;
    size: number;
    score?: number;
}

//#region general helpers

/**
 * Strip version suffix from a JAR basename.
 */
function strip_version(basename: string): string {
    return basename
        .toLowerCase()
        .replace(/\.jar(\.disabled)?$/i, '') // strip extension
        .replace(/^[\[\+\-\d\.]+|(\[[A-Z]+\])/g, '') // strip leading crud like [CLIENT], +, digits
        .replace(/[+\-_\. ]*(mc\d|[_\-\+\.]\d).*/i, '') // strip from version onwards (+1.2, -mc1.7, _v2 etc)
        .trim();
}

/**
 * Run `git log --name-status` and return Map<stripped_basename, change_count>
 * for files under MOD_BASE_DIR in the last `window_size` commits.
 */
async function parse_git_log(window_size: number, known_basenames: Set<string>): Promise<Map<string, number>> {
    const counts = new Map<string, number>();

    const git_mod_dir = MOD_BASE_DIR.replace(new RegExp(`^${RELATIVE_INSTANCE_DIRECTORY}`, 'm'), '');

    const proc = Bun.spawn(['git', 'log', '--name-status', '--diff-filter=ADR', '--find-renames', `-${window_size}`, '--pretty=format:'], {
        cwd: RELATIVE_INSTANCE_DIRECTORY,
        stdout: 'pipe',
        stderr: 'pipe',
    });

    const [stdout_text, stderr_text] = await Promise.all([new Response(proc.stdout).text(), new Response(proc.stderr).text()]);
    await proc.exited;

    if (proc.exitCode !== 0) {
        throw new Error(`git log exited ${proc.exitCode}: ${stderr_text.trim()}`);
    }

    for (const raw_line of stdout_text.split('\n')) {
        const line = raw_line.trim();
        if (!line) continue;

        let file_path: string | undefined;

        if (line.startsWith('R')) {
            // R<score>\t<old_path>\t<new_path> — rename, use new path only (one event)
            const parts = line.split('\t');
            file_path = parts[2];
        } else if (line.startsWith('A\t') || line.startsWith('D\t')) {
            file_path = line.split('\t')[1];
        }

        if (!file_path) continue;

        // Only consider paths under MOD_BASE_DIR
        if (!file_path.startsWith(git_mod_dir)) continue;

        const basename = path.posix.basename(file_path);
        const stripped = strip_version(basename);

        if (!known_basenames.has(stripped)) continue;

        counts.set(stripped, (counts.get(stripped) ?? 0) + 1);
    }

    return counts;
}

/**
 * Score a candidate mod relative to all other mods in its bucket by the impact it can have on its bucket by changing.
 *
 *   freq_exp        = freq ^ 1.5
 *   p80             = sorted_others[floor(n * 0.8)]
 *   clamped_mean    = mean of others where freq_exp <= p80
 *   bucket_cost     = clamped_mean * sum(other sizes)
 *   candidate_cost  = freq_exp * size
 *   score           = candidate_cost / bucket_cost
 */
function compute_layer_weight_of_mod(
    candidate_freq_exp: number,
    candidate_size: number,
    others: { freq_exp: number; size: number }[],
    multipliers: { size?: number; freq?: number } = {},
): number {
    if (others.length === 0) return 0;
    // Never promote a mod that hasn't changed — no savings possible
    if (candidate_freq_exp <= 0) return 0;

    // Only use actively-changing mods to compute bucket churn rate;
    // zero-freq mods drag the mean down and inflate scores artificially
    const active_others = others.filter((o) => o.freq_exp > 0);
    if (active_others.length === 0) return 0;

    // Clamp at 80th percentile to suppress outlier effects on the mean
    const sorted = active_others.map((o) => o.freq_exp).sort((a, b) => a - b);
    const p80 = sorted[Math.floor(sorted.length * 0.8)]!;
    const clamped = sorted.filter((f) => f <= p80);
    const clamped_mean = clamped.reduce((a, b) => a + b, 0) / clamped.length;

    // Size of the whole bucket matters even for stable mods — they still get re-pushed when the layer rebuilds
    const bucket_remaining_size = others.reduce((s, o) => s + o.size, 0);
    const bucket_cost = clamped_mean * bucket_remaining_size;
    const candidate_cost = candidate_freq_exp * (multipliers.freq ?? 1) * (candidate_size * (multipliers.size ?? 1));

    // Score > 1 means this mod costs more to keep in the bucket than the rest of the bucket costs to re-push
    if (bucket_cost === 0) return 0;
    return candidate_cost / bucket_cost;
}

function re_escape(s: string): string {
    return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Return the real byte size of a file, resolving LFS pointer files to their declared size.
 * Bun.file().size returns the pointer file size (~130 B) for LFS-tracked files, not the real size.
 */
async function get_real_file_size(file_path: string): Promise<number> {
    const file = Bun.file(file_path);
    const raw_size = file.size;
    // LFS pointer files are always small; skip reading large files
    if (raw_size < 512) {
        const text = await file.text();
        if (text.startsWith(LFS_HEADER)) {
            const lfs_size = text.match(/^size (\d+)$/m)?.[1];
            if (lfs_size) return parseInt(lfs_size, 10);
        }
    }
    return raw_size;
}

/**
 * Read the real contents of a file, smudging through `git lfs smudge` if it is an LFS pointer.
 * Bun.file().arrayBuffer() returns the raw pointer bytes for LFS-tracked files, not the real content.
 */
async function read_real_file_content(file_path: string): Promise<ArrayBuffer> {
    const file = Bun.file(file_path);
    if (file.size < 512) {
        const text = await file.text();
        if (text.startsWith(LFS_HEADER)) {
            const proc = Bun.spawn(['git', 'lfs', 'smudge', '--skip=false', file_path], {
                cwd: RELATIVE_INSTANCE_DIRECTORY,
                stdin: new TextEncoder().encode(text),
                stdout: 'pipe',
                stderr: 'pipe',
            });
            const [data, stderr_text] = await Promise.all([new Response(proc.stdout).arrayBuffer(), new Response(proc.stderr).text()]);
            await proc.exited;
            if (proc.exitCode !== 0) {
                if (stderr_text.includes("git: 'lfs' is not a git command")) {
                    console.error("ERR: This repo contains lfs files, but lfs is not installed. Make sure to install it first.")
                }
                throw new Error(`git lfs smudge failed for ${file_path}: ${stderr_text.trim()}`);
            }
            return data;
        }
    }
    return file.arrayBuffer();
}

function should_include_mod(tags: string[] | undefined, include_tags: string[] | undefined, exclude_tags: string[] | undefined): boolean {
    if (tags == undefined && include_tags != undefined && include_tags.length > 0) return false;

    let should_be_included = false;
    if (tags != undefined && include_tags != undefined && include_tags.length > 0) {
        for (const include_tag of include_tags) {
            if (tags.includes(include_tag)) {
                should_be_included = true;
                break;
            }
        }
    } else {
        should_be_included = true;
    }

    if (should_be_included && tags != undefined && exclude_tags != undefined && exclude_tags.length > 0) {
        for (const exclude_tag of exclude_tags) {
            if (tags.includes(exclude_tag)) {
                should_be_included = false;
                break;
            }
        }
    }

    return should_be_included;
}

function build_dockerfile_block(
    staging_rel: string,
    bucket_order: BucketName[],
    promoted_order: string[],
    window_size: number,
    container_path: string,
): string {
    const copy_lines = [
        ...bucket_order.map((b) => `COPY ${staging_rel}/mods/${b}/ ${container_path}`),
        ...promoted_order.map((id) => `COPY ${staging_rel}/mods/${id}/ ${container_path}`),
    ];

    return [
        MARKER_START,
        `# Generated: ${new Date().toISOString()}  window: ${window_size} commits`,
        `# Buckets: ${bucket_order.length}  Promoted: ${promoted_order.join(', ') || 'none'}`,
        '',
        ...copy_lines,
        MARKER_END,
    ].join('\n');
}

//#region split mods to layers
export async function package_image(
    target_dockerfile?: string,
    container_path?: string,
    options: {
        dry?: boolean;
        include_tags?: string[];
        exclude_tags?: string[];
        size_multiplier?: number;
        frequency_multiplier?: number;
    } = {},
): Promise<void> {
    if (PACKAGING == undefined) {
        console.error("ERR: Missing config settings for packaging. Make sure to run 'packscripts package init' first.");
        return;
    } else if (PACKAGING.IMAGE?.GIT_CHANGE_WINDOW == undefined || PACKAGING.IMAGE?.STAGING_DIRECTORY == undefined) {
        console.error('ERR: Missing config settings for imaging under PACKGAING.IMAGING.(GIT_CHANGE_WINDOW|STAGING_DIRECTORY).');
        return;
    }

    if (target_dockerfile == undefined) {
        console.error('ERR: Missing target dockerfile path (argument 1), so we know what dockerfile to modify.');
        return;
    } else if (container_path == undefined) {
        console.log('ERR: Missing target directory path inside image (argument 2).');
        return;
    }

    const staging_dir = PACKAGING.IMAGE.STAGING_DIRECTORY.replace(/[/\\]+$/, '');

    console.info('Checking git availability...');
    if (!(await is_git_available(RELATIVE_INSTANCE_DIRECTORY))) {
        console.error('ERR: git is not available. Git history is required for package image.');
        return;
    }

    console.info('Loading mod index...');
    const mod_map = await read_saved_mods(ANNOTATED_FILE);

    // load past promotion state
    const state_path = PACKAGING.PACKAGE_DIRECTORY + 'image_state.json';
    let image_state: ImageState = { promoted: {} };
    const state_file = Bun.file(state_path);
    if (await state_file.exists()) {
        try {
            image_state = await state_file.json();
        } catch {
            console.warn('W: Could not parse image_state.json — starting fresh.');
            image_state = { promoted: {} };
        }
    }

    console.info(`Parsing git log (last ${PACKAGING.IMAGE.GIT_CHANGE_WINDOW} commits)...`);
    // build the set of known stripped basenames from enabled mods
    const known_basenames = new Set<string>();
    for (const [, mod] of mod_map) {
        if (!mod.enabled || !should_include_mod(mod.tags, options.include_tags, options.exclude_tags)) continue;
        known_basenames.add(strip_version(path.basename(mod.file_path)));
    }
    let change_counts: Map<string, number>;
    try {
        change_counts = await parse_git_log(PACKAGING.IMAGE.GIT_CHANGE_WINDOW, known_basenames);
    } catch (err) {
        console.error('ERR: Failed to run git log:', String(err));
        return;
    }

    // assign mods to buckets and build list of change frequencies
    const buckets = new Map<BucketName, ModEntry[]>();
    const mod_entries: ModEntry[] = [];
    for (const [mod_id, mod] of mod_map) {
        if (!mod.enabled || !should_include_mod(mod.tags, options.include_tags, options.exclude_tags)) continue;

        const file = Bun.file(mod.file_path);
        if (!(await file.exists())) {
            console.warn(`W: File for mod ${mod_id} missing on disk, skipping.`);
            continue;
        }

        const stripped_name = strip_version(path.basename(mod.file_path));
        const change_count = change_counts.get(stripped_name) ?? 0;
        const frequency = change_count / PACKAGING.IMAGE.GIT_CHANGE_WINDOW;
        const bucket = BUCKET_NAMES[mod.update_state.source_type];
        const mod_entry = {
            mod_id,
            stripped_basename: stripped_name,
            file_path: mod.file_path,
            bucket: bucket,
            freq: frequency,
            freq_exp: Math.pow(frequency, 1.5),
            size: await get_real_file_size(mod.file_path),
        };

        mod_entries.push(mod_entry);

        // console.debug(
        //     `[debug] ${mod_entry.mod_id}: stripped="${stripped_name}" freq_raw=${change_count ?? 0} freq=${mod_entry.freq} freq_exp=${mod_entry.freq_exp}`,
        // );

        if (!buckets.has(bucket)) buckets.set(bucket, []);
        buckets.get(bucket)!.push(mod_entry);
    }

    // Score and promote mods by weight and age
    const now = new Date();
    const newly_promoted: string[] = [];
    const newly_demoted: string[] = [];

    for (const [, mod_entries] of buckets) {
        for (const mod_entry of mod_entries) {
            const others = mod_entries.filter((m) => m.mod_id !== mod_entry.mod_id).map((m) => ({ freq_exp: m.freq_exp, size: m.size }));

            const score = compute_layer_weight_of_mod(mod_entry.freq_exp, mod_entry.size, others, {
                size: options.size_multiplier,
                freq: options.frequency_multiplier,
            });
            mod_entry.score = score;
            const already_promoted = mod_entry.mod_id in image_state.promoted;

            if (!already_promoted && score > 1.0 && mod_entry.size > TEN_MiB) {
                image_state.promoted[mod_entry.mod_id] = {
                    promoted_at: now.toISOString(),
                    bucket: mod_entry.bucket,
                    last_score: score,
                };
                newly_promoted.push(mod_entry.mod_id);
            } else if (already_promoted) {
                const pstate = image_state.promoted[mod_entry.mod_id]!;
                pstate.last_score = score; // always refresh

                const days_since = (now.getTime() - new Date(pstate.promoted_at).getTime()) / MS_PER_DAY;
                if (score < 0.8 && days_since > 30) {
                    delete image_state.promoted[mod_entry.mod_id];
                    newly_demoted.push(mod_entry.mod_id);
                }
            }
        }
    }

    // Deduplicate and drop promoted entries for mods no longer in the mod index
    const promoted_ids = new Set(Object.keys(image_state.promoted));
    for (const id of [...promoted_ids]) {
        if (!mod_map.has(id)) {
            delete image_state.promoted[id];
            promoted_ids.delete(id);
        }
    }

    const promoted_entries: ModEntry[] = [];
    const bucket_remaining = new Map<BucketName, ModEntry[]>();

    for (const mod_entry of mod_entries) {
        if (promoted_ids.has(mod_entry.mod_id)) {
            promoted_entries.push(mod_entry);
        } else {
            if (!bucket_remaining.has(mod_entry.bucket)) bucket_remaining.set(mod_entry.bucket, []);
            bucket_remaining.get(mod_entry.bucket)!.push(mod_entry);
        }
    }

    // Build final occupied buckets for ones that still have mods in them
    const occupied_buckets = new Map<BucketName, ModEntry[]>();
    for (const [bucket, mod_entries] of bucket_remaining) {
        if (mod_entries.length > 0) occupied_buckets.set(bucket, mod_entries);
    }

    // Order layer buckets by ascending mean freq of remaining (non-promoted) members
    const mean_freq = (ms: ModEntry[]) => ms.reduce((s, m) => s + m.freq, 0) / ms.length;
    const sorted_bucket_entries = [...occupied_buckets.entries()].sort((a, b) => mean_freq(a[1]) - mean_freq(b[1]));
    const sorted_bucket_names = sorted_bucket_entries.map(([name]) => name);

    // Sort promoted entries by their last score
    const sorted_promoted = [...promoted_entries].sort(
        (a, b) => (image_state.promoted[a.mod_id]?.last_score ?? 0) - (image_state.promoted[b.mod_id]?.last_score ?? 0),
    );
    const sorted_promoted_ids = sorted_promoted.map((e) => e.mod_id);

    if (options.dry) {
        console.info('\n--- DRY RUN: layer plan ---\n');

        if (sorted_bucket_entries.length === 0) {
            console.info('(no occupied buckets)');
        }
        for (const [bucket_name, members] of sorted_bucket_entries) {
            console.info(
                `Bucket: ${bucket_name}  (${members.length} mod${members.length === 1 ? '' : 's'}, ` +
                    `mean freq ${mean_freq(members).toFixed(4)})`,
            );
            for (const m of members) {
                console.info(
                    `  ${m.mod_id.padEnd(40)} freq=${m.freq.toFixed(4)}  ` +
                        `score=${m.score != undefined ? (isFinite(m.score) ? m.score.toFixed(4) : 'inf') : '?'}  ` +
                        `size=${(m.size / 1024 / 1024).toFixed(2)} MiB`,
                );
            }
        }

        if (sorted_promoted.length > 0) {
            console.info('\nPromoted mods:');
            for (const e of sorted_promoted) {
                const sc = image_state.promoted[e.mod_id]?.last_score ?? 0;
                console.info(
                    `  ${e.mod_id.padEnd(40)} freq=${e.freq.toFixed(4)}  ` +
                        `score=${isFinite(sc) ? sc.toFixed(4) : 'inf'}  ` +
                        `size=${(e.size / 1024 / 1024).toFixed(2)} MiB`,
                );
            }
        } else {
            console.info('\n(no promoted mods)');
        }

        console.info('\n--- Generated Dockerfile block ---\n');
        const block = build_dockerfile_block(
            staging_dir,
            sorted_bucket_names,
            sorted_promoted_ids,
            PACKAGING.IMAGE.GIT_CHANGE_WINDOW,
            container_path,
        );
        console.info(block);
        console.info('\n(dry run — no files written)');
        return;
    }

    if (!options.dry && path_is_directory(staging_dir)) {
        console.log('Deleting old staging directory...');
        await rm(staging_dir, { recursive: true });
    }
    await mkdir(path.join(staging_dir, 'mods'), { recursive: true });

    const populated_buckets = new Set<BucketName>();
    const populated_promoted = new Set<string>();

    console.info('Copying files...');
    // Copy non-promoted mods into their bucket subdirectory
    for (const [bucket_name, mod_entries] of occupied_buckets) {
        const bucket_dir = path.join(staging_dir, 'mods', bucket_name);
        await mkdir(bucket_dir, { recursive: true });

        await run_pool(
            mod_entries.map((entry) => async () => {
                const file = Bun.file(entry.file_path);
                if (!(await file.exists())) {
                    console.warn(`W: Mod file missing on disk: ${entry.file_path}, skipping.`);
                    return;
                }
                const data = await read_real_file_content(entry.file_path);
                await Bun.write(path.join(bucket_dir, path.basename(entry.file_path)), data);
                populated_buckets.add(bucket_name);
            }),
            8,
        );
    }

    // Copy each promoted mod into its own subdirectory (<staging>/mods/<mod_id>/)
    await run_pool(
        promoted_entries.map((entry) => async () => {
            const mod_dir = path.join(staging_dir, 'mods', entry.mod_id);
            await mkdir(mod_dir, { recursive: true });

            const file = Bun.file(entry.file_path);
            if (!(await file.exists())) {
                console.warn(`W: Mod file missing on disk: ${entry.file_path}, skipping.`);
                return;
            }
            const data = await read_real_file_content(entry.file_path);
            await Bun.write(path.join(mod_dir, path.basename(entry.file_path)), data);
            populated_promoted.add(entry.mod_id);
        }),
        8,
    );

    console.info('Patching Dockerfile...');
    const dockerfile_file = Bun.file(target_dockerfile);
    if (!(await dockerfile_file.exists())) {
        console.error(`ERR: Missing dockerfile at: ${target_dockerfile}`);
        return;
    }

    let dockerfile = await dockerfile_file.text();

    // Normalize line endings to LF
    dockerfile = dockerfile.replace(/\r\n/g, '\n');

    // Strip existing block if present
    dockerfile = dockerfile.replace(MARKER_RE, '\n');

    // Find ENTRYPOINT
    const df_lines = dockerfile.split('\n');
    const ep_idx = df_lines.findIndex((l) => /^\s*ENTRYPOINT\b/.test(l));
    if (ep_idx === -1) {
        console.error('ERR: No ENTRYPOINT instruction found in Dockerfile. Cannot patch.');
        return;
    }

    const emit_buckets = sorted_bucket_names.filter((b) => populated_buckets.has(b));
    const emit_promoted = sorted_promoted_ids.filter((id) => populated_promoted.has(id));
    const block = build_dockerfile_block(staging_dir, emit_buckets, emit_promoted, PACKAGING.IMAGE.GIT_CHANGE_WINDOW, container_path);

    // Insert our block into existing lines
    df_lines.splice(ep_idx, 0, block, '');
    dockerfile = df_lines.join('\n');
    // Collapse any run of 3+ blank lines down to 2 (one blank line visually)
    dockerfile = dockerfile.replace(/\n{3,}/g, '\n\n');

    await Bun.write(target_dockerfile, dockerfile);
    await Bun.write(state_path, JSON.stringify(image_state, null, 4));

    console.info(
        `\nBuilt layer plan: ${occupied_buckets.size} bucket${occupied_buckets.size === 1 ? '' : 's'}, ` +
            `${promoted_ids.size} promoted ` +
            `(${newly_promoted.length} newly promoted, ${newly_demoted.length} demoted this run).`,
    );
    console.info(`Staging directory written to ${staging_dir}/.`);
    console.info(`Dockerfile patched at ${target_dockerfile}.`);
}
